Dataset sharing permissions
birdspotter-project/COS397 pull request #49
Opened 2021-03-15 18:41 UTC by NickKania

Migrations:
- Add shared_with field to dataio.dataset 
- Set all default permissions to false
By default, django gives users all permissions to each model, this is not correct for out implementation and although we are using group based permissions, it would still be nice to not have that hanging out in the background.
Changes:
- Add sharing for datasets
- Add back-end permissions for Editing, Sharing, and Queuing datasets to go along with hiding the links in the UI
- UI tweaks based on feedback during demo
- Update test that was failing in docker due to a hard-coded primary-key value 

*There are currently no tests written for sharing, those will take a considerable amount of time to write

2021-03-16 02:50 UTC, NickKania commented
Reverting due to issues caused with groups. Removing the default permissions breaks group permissions, and as we are not checking for actual permissions, but rather basing authorization off of the user's group, there is no current side effect of this.

2021-03-19 16:08 UTC, devinchristianson requested changes
I was able to fix most linter issues, but there was one I had a question about. Otherwise, everything looks good.

2021-03-19 16:08 UTC, devinchristianson commented on birdspotter/birdspotter/dataio/views.py
> +from django.contrib.auth.decorators import login_required, user_passes_test
user_passes_test is unused according to the linter - is this because there is missing code, or does it just need to be removed?

2021-03-19 16:27 UTC, devinchristianson approved these changes

2021-03-19 16:27 UTC, merged